# Generated by Django 5.2 on 2025-04-25 08:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Health_Facilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, null=True)),
                ("amenity", models.CharField(max_length=80, null=True)),
                ("healthcare", models.CharField(max_length=80, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Health_Facilities",
            },
        ),
        migrations.CreateModel(
            name="Incidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fire", "Fire"),
                            ("medical", "Medical"),
                            ("crime", "Crime"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(max_length=200, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="emergency_images/"
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Incidences",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Locations",
            },
        ),
    ]
