# Generated by Django 5.2 on 2025-04-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contact_information", models.CharField(max_length=15)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("firefighter", "Firefighter"),
                            ("paramedic", "Paramedic"),
                            ("police", "Police"),
                            ("general", "General Responder"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
