# Generated by Django 5.2 on 2025-04-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidence',
            old_name='name',
            new_name='area_name',
        ),
        migrations.RemoveField(
            model_name='incidence',
            name='location',
        ),
    ]
