# Generated by Django 5.2 on 2025-04-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0002_responder"),
    ]

    operations = [
        migrations.AddField(
            model_name="responder",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("on_duty", "On Duty"),
                    ("unavailable", "Unavailable"),
                ],
                default="available",
                max_length=50,
            ),
        ),
    ]
