# Generated by Django 5.2 on 2025-04-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0004_incidentreport_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidence",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="emergency_images/"
            ),
        ),
        migrations.AddField(
            model_name="incidence",
            name="responders",
            field=models.ManyToManyField(
                related_name="emergencies_handled", to="emergency.responder"
            ),
        ),
    ]
