# Generated by Django 5.2 on 2025-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0005_incidence_image_incidence_responders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidence",
            name="status",
            field=models.CharField(
                choices=[
                    ("low_risk", "Low risk"),
                    ("moderate_risk", "Moderate risk"),
                    ("high_risk", "High risk"),
                ],
                max_length=50,
            ),
        ),
    ]
