# Generated by Django 5.2 on 2025-04-13 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0006_alter_incidence_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="linked_emergency",
        ),
        migrations.RemoveField(
            model_name="incidence",
            name="responders",
        ),
        migrations.RemoveField(
            model_name="incidence",
            name="location_name",
        ),
        migrations.RemoveField(
            model_name="incidence",
            name="status",
        ),
        migrations.RemoveField(
            model_name="incidence",
            name="title",
        ),
        migrations.AddField(
            model_name="incidence",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="incidence",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="incidence",
            name="severity",
            field=models.CharField(
                choices=[("high", "High"), ("moderate", "Moderate"), ("high", "High")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incidence",
            name="category",
            field=models.CharField(
                choices=[("fire", "Fire"), ("medical", "Medical"), ("crime", "Crime")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incidence",
            name="description",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="IncidentReport",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Responder",
        ),
    ]
