# Generated by Django 5.2 on 2025-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0007_remove_location_linked_emergency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidence",
            name="category",
        ),
        migrations.RemoveField(
            model_name="incidence",
            name="name",
        ),
        migrations.AddField(
            model_name="incidence",
            name="type",
            field=models.CharField(
                choices=[("fire", "Fire"), ("medical", "Medical"), ("crime", "Crime")],
                max_length=20,
                null=True,
            ),
        ),
    ]
