# Generated by Django 5.2 on 2025-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0008_remove_incidence_category_remove_incidence_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incidence",
            old_name="type",
            new_name="category",
        ),
        migrations.AddField(
            model_name="incidence",
            name="name",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
