# Generated by Django 5.2 on 2025-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0009_rename_type_incidence_category_incidence_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidence",
            options={"verbose_name_plural": "Incidences"},
        ),
    ]
