# Generated by Django 5.2 on 2025-04-15 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0010_alter_incidence_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidence",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
