# Generated by Django 5.2 on 2025-04-18 08:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0011_alter_incidence_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Health_Facilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("amenity", models.CharField(max_length=80)),
                ("healthcare", models.CharField(max_length=80)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Health_Facilities",
            },
        ),
    ]
